### ISSUE TITLE
Don't send trajectories when jog is inactive

### ISSUE THREAD

**Issue by machinekoder** [UTNuclearRoboticsPublic/jog_arm#12]
Sending zero velocity trajectory messages when no jog is active (all input values 0) does prevent other trajectory sources such as moveit from driving the controller.

Therefore, It would make sense to stop sending zero velocity messages when no jog is currently active.

**Comment by AndyZe** [comment]
3a07997

**Comment by machinekoder** [comment]
Excellent, thank you.
