### ISSUE TITLE
Cannot jog across +-0 boundary

### ISSUE THREAD

**Issue by machinekoder** [UTNuclearRoboticsPublic/jog_arm#16]
At the moment it's impossible to jog across the +-0 boundary e.g. in the X axis. After moving the arm with to the other side using MoveIt, I can again in the other direction until I hit the 0 point.

See https://youtu.be/ryge-AOryfE

**Comment by AndyZe** [comment]
Hmm, I don't see this problem. Is it giving a singularity warning?

**Comment by machinekoder** [comment]
I found the reason: This happens when the robot runs into a joint limit on the base joint. Makes totally sense that jogging stops, in this case, is just a little bit unintuitive. So that's just a joint limit problem.
