### ISSUE TITLE
jog_arm_server doesn't stop cleanly

### ISSUE THREAD

**Issue by machinekoder** [UTNuclearRoboticsPublic/jog_arm#58]
When stopping the `jog_arm_server` via ros shutdown, the `jog_arm_server` just keeps running and needs to be `escalated to SIGTERM`. A check for ROS shutdown is probably missing.

**Comment by AndyZe** [comment]
19dd00a might have fixed this. There was a while loop that did not contain a ros::ok(). It seems to be stopping much faster for me. Will close, for now.
