### ISSUE TITLE
Add joint limit checking

### ISSUE THREAD

**Issue by AndyZe** [UTNuclearRoboticsPublic/jog_arm#6]

**Comment by AndyZe** [comment]
@gopikaajaykumar This is something you could work on. I planned to use the [joint_limits_interface](https://github.com/ros-controls/ros_control/wiki/joint_limits_interface).

**Comment by gopikaajaykumar** [comment]
Thanks Andy!On Mar 22, 2018 11:36 AM, AndyZe <notifications@github.com> wrote:@gopikaajaykumar This is something you could work on. I planned to use the joint_limits_interface.

**Comment by machinekoder** [comment]
I can confirm this.

Another option would be to check the cartesian position after generating the new pose if any other axis than the intended one was moved, then we are in a joint limit.

**Comment by AndyZe** [comment]
eb3f730
