### ISSUE TITLE
Misleading function name

### ISSUE THREAD

**Issue by azhural** [UTNuclearRoboticsPublic/jog_arm#63]
`insertRedundantPointsIntoTrajectory(trajectory_msgs::JointTrajectory& trajectory, int count)`

does not insert `count ` points (but two less), nor is the final trajectory of length `count` (off by one).

Stumbled over this while trying to figure out why the simulation trajectories were of length 29 and only 1 on the real robot.

**Comment by AndyZe** [comment]
8cb9297
