### ISSUE TITLE
Spacemouse model selection 

### ISSUE THREAD

**Issue by stevensu1838** [UTNuclearRoboticsPublic/jog_arm#72]
Hi Sir,

Can you please show me which of the following two mice will be compatible with you package? I am going to buy one. And is a wireless one better than a  wired one? Thanks a lot 

![image](https://user-images.githubusercontent.com/25648734/48041182-ed012800-e1e0-11e8-975c-9c26a673d907.png)

**Comment by AndyZe** [comment]
They will both work. I like the wired version a little better so you don't need to worry about charging it, but that's a matter of preference.
