### ISSUE TITLE
Kinetic and Kinetic-devel, Which branch to use?

### ISSUE THREAD

**Issue by stevensu1838** [UTNuclearRoboticsPublic/jog_arm#74]
Hi Sir,
I am running kinetic-devel branch from iron-ox/ur_modern_driver on ROS kinetic and my target is to use a 3D mouse to control a UR5 (firstly in Gazebo, then on the real robot) with your jog_arm package. Please forgive me if it is silly, does it works well with Gazebo? Kinetic and Kinetic-devel of your excellent package, Which branch shall to use?

secondly, I saw you comment in iron-ox/ur_modern_driver and you kindly explained the steps to setup:

    step3.put the attached launch and config files somewhere you can find them
    step4.launch the jog_arm launch file
    roslaunch ~/Desktop/my/path/jog_node.launch

My question is if I've put your attached files somewhere do I still need to git clone your whole jog_arm package? If so, can I just put the two files into your package after downloading? Thanks a million

Steven

**Comment by AndyZe** [comment]
Hi @stevensu1838,

- Yes, it works in Gazebo.
- Use the kinetic branch.
- You will need to clone the package and you can put those files in the package if you want to. Personally, I would put them somewhere else so I can back them up on Github.
