### ISSUE TITLE
Use a 3D sensor(Kinect/Intel real sense) to produce the pointcloud of the environment of UR5 for collsion avoidance?

### ISSUE THREAD

**Issue by stevensu1838** [UTNuclearRoboticsPublic/jog_arm#81]
Hi Andy,
The jog arm package is kind of related to moveit. May I please ask if I can use a 3D sensor(Kinect/Intel real sense) to produce the pointcloud of the environment of UR5 for collision avoidance while jogging? like I wanna ensure the tool of UR5 doesn't crash into the table.

Further, once you told me it is easier to add on more sensors with in ROS with jog arm. Normally, in your project what type of sensors do you use together with jog arm package? Thanks a million.

**Comment by AndyZe** [comment]
MoveIt! has a [tutorial](http://docs.ros.org/kinetic/api/moveit_tutorials/html/doc/perception_pipeline/perception_pipeline_tutorial.html) on that. The Octomap collision representation that MoveIt! creates should work with jog_arm, but I haven't tested that myself. (I have tested other collision types, though.)

You'll have to make a camera_link frame in your URDF to define where the camera is attached. And I think almost any RGBD camera would be OK, but we like Intel Realsense. They aren't extremely accurate, but good for the price.
