### ISSUE TITLE
Invalid argument passed to lookupTransform argument source_frame in tf2 frame_ids cannot be empty

### ISSUE THREAD

**Issue by AshwinR96** [UTNuclearRoboticsPublic/jog_arm#86]
I am trying to run jog_arm to control my UR3 simulation on Gazebo. But I am getting this error:

>/jog_arm_server: Invalid argument passed to lookupTransform argument source_frame in tf2 frame_ids cannot be empty

What do I need to do fix this?

My jog_settings.yaml has this:
`gazebo: true 

collision_check: true

command_in_type: "unitless" 
scale: 

  linear:  0.003  

  rotational:  0.006  

  joint: 0.01 

cartesian_command_in_topic:  jog_arm_server/delta_jog_cmds 

joint_command_in_topic: jog_arm_server/joint_delta_jog_cmds

command_frame:  base_link  

incoming_command_timeout:  5  

joint_topic:  joint_states

move_group_name:  manipulator  

lower_singularity_threshold:  30  

hard_stop_singularity_threshold: 45 

lower_collision_proximity_threshold: 0.1 

hard_stop_collision_proximity_threshold: 0.005

planning_frame: base_link 

low_pass_filter_coeff: 2.  

publish_period: 0.008 

publish_delay: 0.005  

collision_check_rate: 5 

warning_topic: jog_arm_server/warning

joint_limit_margin: 0.1

command_out_topic: arm_controller/command

command_out_type: trajectory_msgs/JointTrajectory

publish_joint_positions: true

publish_joint_velocities: true

publish_joint_accelerations: false`

**Comment by AndyZe** [comment]
You just need to make sure the incoming message has a header.stamp.frame_id. I'll push a fix later today

**Comment by AshwinR96** [comment]
Okay, thank you

**Comment by AndyZe** [comment]
Commit 13ad62a should take care of this. The `command_frame` from your yaml file is automatically put on all incoming msgs. Let me know if it still isn't working for you.
