### ISSUE TITLE
Trajectories can’t be previewed in RViz

### ISSUE THREAD

**Issue by Kevinlinpr** [UTNuclearRoboticsPublic/jog_arm#92]
Is there only two way to preview the trajectories ? one is via gazebo another is real robot.
Trajectories can’t be previewed in RViz.

**Comment by machinekoder** [comment]
I'm not sure how this relates to jog_arm. But you can preview trajectories in RViz.

**Comment by AndyZe** [comment]
^That's the right answer. jog_arm is for instantaneous commands, not trajectories.
