### ISSUE TITLE
Is there a way to know or set the velocity of jogging in unitless mode? 

### ISSUE THREAD

**Issue by stevensu1838** [UTNuclearRoboticsPublic/jog_arm#96]
Hi Andy,

Just ask this question here to clarify the control of velocity with jog_arm package. Coz this might be useful for others who need to control the TCP velocity precisely for some certain scenarios.

When I **switch from "unitless" to "speed_units"** in the the jog_settings.yaml, what else modification shall make? Form my own experience, only changing from "unitless" to "speed_units" make the jogging freeze after a short time of control. 

Thank you so much for your patience and constant support. You are really something.

BR,
Steven

**Comment by stevensu1838** [comment]
Hi Andy,
Please take a look at the video clip of my problem after switching to speed_unit. The jogging doesn't last long.
https://drive.google.com/file/d/1TraAR9h--d0biwMyuCkUvZSl91JnPCbJ/view?usp=sharing

**Comment by Gutesnacht** [comment]
stevensu1838 <notifications@github.com> schrieb am Mo., 8. Apr. 2019, 03:17:
